-- CreateEnum
CREATE TYPE "TodoPriority" AS ENUM ('IMPORTANT', 'MEDIUM', 'EASY');

-- AlterTable
ALTER TABLE "Todo" ADD COLUMN "dueDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Todo" ADD COLUMN "priority" "TodoPriority" NOT NULL DEFAULT 'MEDIUM';
